name: Run Windows Command

on:
  push:
    branches:
      - main

jobs:
  run-command:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        architecture: 'x64'
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true

    - name: AssureIT
      run: |
        .\Run.bat -run -project_location "Projects\Hackaton" -release "UI" -testset "Scenario_03"
        
    - name: Publish results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: Projects/Hackaton/Results/TestExecution/UI/Sample/Latest
        
    - name: Deploy to GitHub Pages
      uses: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && success() && contains(runner.os, 'Windows') && contains(matrix.java, '17') ? 'peaceiris/actions-gh-pages@v3' : 'some/other-action@v1' }}
      with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: Projects/Hackaton/Results/TestExecution/UI/Sample/Latest/

        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
