name: Run Windows Command

on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  run-command:
    runs-on: windows-latest
    if: always()
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        architecture: 'x64'
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
         
    - name: AssureIT
      run: |
        .\Run.bat -run -project_location "Projects\Hackaton" -release "UI" -testset "Scenario_03"
        
    - name: Publish results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: Projects/Hackaton/Results/TestExecution/UI/Sample/Latest
        
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: Projects/Hackaton/Results/TestExecution/UI/Sample/Latest
        retention-days: 1
                   
    - name: Setup Pages
      uses: actions/configure-pages@v2
       
    - uses: actions/download-artifact@v2
      with:
        name: 'github-pages'
           
    - name: Deploy to GitHub Pages
      id: github-pages
      uses: actions/deploy-pages@v1
      index-file: 'extent.html
